/*
 Aaron Purinton
Egnigma-Like-Machine
 */
package egnigma;
import java.util.*;
import java.io.*;

/**
 *
 * @author aepur
 */
public class Enigma extends javax.swing.JFrame {
    Scanner in;
    int r0 = 1, r1 = 1, r2 = 1;//Rotar values
    int A = 'A', Z = 'Z';
    int[] init = new int[26];
    int[] map = new int[26];
    boolean toCo = true;
    
    /**
     * Creates new form NewJFrame
     */
    
    public Enigma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r0Up = new javax.swing.JButton();
        r0Label = new javax.swing.JLabel();
        r0Down = new javax.swing.JButton();
        r1Up = new javax.swing.JButton();
        r1Label = new javax.swing.JLabel();
        r1Down = new javax.swing.JButton();
        r2Up = new javax.swing.JButton();
        r2Label = new javax.swing.JLabel();
        r2Down = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        originalText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        translationText = new javax.swing.JTextArea();
        Pair = new javax.swing.JButton();
        DialSet = new javax.swing.JButton();
        Tanslate = new javax.swing.JButton();
        toFrom = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Egnigma");
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        r0Up.setText("↑");
        r0Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r0UpActionPerformed(evt);
            }
        });

        r0Label.setText("1");

        r0Down.setText("↓");
        r0Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r0DownActionPerformed(evt);
            }
        });

        r1Up.setText("↑");
        r1Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1UpActionPerformed(evt);
            }
        });

        r1Label.setText("1");

        r1Down.setText("↓");
        r1Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1DownActionPerformed(evt);
            }
        });

        r2Up.setText("↑");
        r2Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2UpActionPerformed(evt);
            }
        });

        r2Label.setText("1");

        r2Down.setText("↓");
        r2Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2DownActionPerformed(evt);
            }
        });

        originalText.setColumns(20);
        originalText.setLineWrap(true);
        originalText.setRows(5);
        originalText.setText("Sample Text. This is a \"test!\"");
        jScrollPane2.setViewportView(originalText);

        translationText.setColumns(20);
        translationText.setRows(5);
        jScrollPane3.setViewportView(translationText);

        Pair.setText("Configure Pair");
        Pair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PairActionPerformed(evt);
            }
        });

        DialSet.setText("Set Dials");
        DialSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialSetActionPerformed(evt);
            }
        });

        Tanslate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tanslate.setText("Translate");
        Tanslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanslateActionPerformed(evt);
            }
        });

        toFrom.setText("To Code");
        toFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r0Up)
                            .addComponent(r0Down)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(r0Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r1Up)
                            .addComponent(r1Down)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(r1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r2Down)
                            .addComponent(r2Up)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(r2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Tanslate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DialSet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Pair)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(toFrom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(270, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r2Up)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r2Down))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r0Up)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r0Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r0Down))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r1Up)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r1Down)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DialSet)
                    .addComponent(Pair))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toFrom)
                        .addGap(35, 35, 35)
                        .addComponent(Tanslate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r0UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r0UpActionPerformed
        // TODO add your handling code here:
        r0++;
        if(r0>26){
            r0=1;
            r1UpActionPerformed(evt);
        }
        r0Label.setText(r0+"");
    }//GEN-LAST:event_r0UpActionPerformed

    private void r0DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r0DownActionPerformed
        // TODO add your handling code here:
        r0--;
        if(r0<0){
            r0=26;
        }
        r0Label.setText(r0+"");
    }//GEN-LAST:event_r0DownActionPerformed

    private void r1DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1DownActionPerformed
        // TODO add your handling code here:
        r1--;
        if(r1<0){
            r1=26;
        }
        r1Label.setText(r1+"");
    }//GEN-LAST:event_r1DownActionPerformed

    private void DialSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialSetActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("Dial.txt");
            in = new Scanner(file);
            //System.out.println("Here");
            //System.out.println(in.nextLine());
            r0 = in.nextInt()%26 +1;
            r1 = in.nextInt()%26 +1;
            r2 = in.nextInt()%26 +1;
            //System.out.println(r0+" "+r1+" "+r2);
            in.close();
        }catch(Exception e){System.out.println("ERROR, Dials not set\n"+e);}
            r0Label.setText(r0+"");
            r1Label.setText(r1+"");
            r2Label.setText(r2+"");
    }//GEN-LAST:event_DialSetActionPerformed

    private void PairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PairActionPerformed
        // TODO add your handling code here:
        defaul();
        try{
            File file = new File("today.txt");
            in = new Scanner(file);
            int i = 0;
            while(in.hasNext()){
                map[i]=(int)(in.next().charAt(0));
                if(map[i] < A || map[i]>Z){
                    defaul();
                    System.out.println("ERROR, pairing not compatable, using default");
                    break;
                }
                for(int k=i-1; i<0; i--){
                    if(map[i] == map[k]){
                        defaul();
                        System.out.println("ERROR, pairing not compatable, using default");
                        break;
                    }
                }
                //System.out.println((char)map[i]);
                i++;
            }
            
            in.close();
        }catch(Exception e){
            System.out.println("ERROR, Pairing Failed, using default\n"+e);
        }
        
    }//GEN-LAST:event_PairActionPerformed

    private void r1UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1UpActionPerformed
        r1++;
        if(r1>26){
            r1=1;
            r2UpActionPerformed(evt);
        }
        r1Label.setText(r1+"");
    }//GEN-LAST:event_r1UpActionPerformed

    private void r2UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2UpActionPerformed

        r2++;
        if(r2>26){
            r2=1;
        }
        r2Label.setText(r2+"");
    }//GEN-LAST:event_r2UpActionPerformed

    private void r2DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2DownActionPerformed

        r2--;
        if(r2<0){
            r2=26;
        }
        r2Label.setText(r2+"");
    }//GEN-LAST:event_r2DownActionPerformed

    private void TanslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanslateActionPerformed

        String original = originalText.getText().toUpperCase();
        String code = "";
        int r0clone = r0;
        int r1clone = r1;
        int r2clone = r2;
        int length = original.length();
        
        //System.out.println(original);
        
        if(toCo){
        for(int i = 0; i < length; i++,r0clone++){
            
            //added
            if(original.charAt(i) < 65 || original.charAt(i) > 90){ /*r0clone--;*/ code += original.charAt(i); continue;}
            
            if(r0clone>26){
                r0clone = 0;
                r1clone++;
            }
            if(r1clone>26){
                r1clone=0;
                r2clone++;
            }
            if(r2clone>26){
                r2clone=0;
            }
            
            int x = flip(original.charAt(i))-A;//0-25
            //System.out.println("x= "+x);
            code+=((char)(unflip(((x+r0clone+r1clone+r2clone)%26)+A)));
        }
        //r0Label.setText("idaf");
        
        //System.out.println(code);
        translationText.setText(code);
        }
        
        else{
             for(int i = 0; i < length; i++,r0clone++){
                 
                 if(original.charAt(i)<0x41 || original.charAt(i)> 0x5A){/*r0clone--;*/ code += original.charAt(i); continue;}
                 
            if(r0clone>26){
                r0clone = 0;
                r1clone++;
            }
            if(r1clone>26){
                r1clone=0;
                r2clone++;
            }
            if(r2clone>26){
                r2clone=0;
            }
            
            int x = flip(original.charAt(i))-A;//0-25
            //System.out.println("x= "+x);
            //System.out.println(flip(((x-r0clone-r1clone-r2clone)%26)+A));
            //code+=((char)(flip(((x-r0clone-r1clone-r2clone)%26)+A)));
            
            x = (x-r0clone-r1clone-r2clone);
            //System.out.println(x);
            while(x<0){
                x+=26;
            }
            code+=(char)unflip(x+A);
        }
        //r0Label.setText("idaf");
        
        //System.out.println(code);
        translationText.setText(code);
        
        }
    }//GEN-LAST:event_TanslateActionPerformed
    
    private int unflip(int x){
        for(int i = 0; i<26; i++){
            if(x==map[i]){
                return init[i];
            }
        }
        return -1;
    }
    
    private int flip(int x){
        for(int i = 0; i<26; i++){
            if(x==init[i]){
                return map[i];
            }
        }
        return -1;
    }
    
    private void toFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFromActionPerformed
        // TODO add your handling code here:
        toCo=!toCo;
        if(toCo){
            toFrom.setText("To Code");
        }else{
            toFrom.setText("From Code");
        }
    }//GEN-LAST:event_toFromActionPerformed
    
    private void defaul(){
        for(int i=A;i<=Z;i++){
            init[i-A] = i;
            map[i-A] = i;
        }
    }
    
    /**
     * @param args the command line arguments
     *         try{
        
        }catch(Exception e){System.out.println("ERROR,");}
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enigma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enigma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enigma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enigma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enigma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DialSet;
    private javax.swing.JButton Pair;
    private javax.swing.JButton Tanslate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea originalText;
    private javax.swing.JButton r0Down;
    private javax.swing.JLabel r0Label;
    private javax.swing.JButton r0Up;
    private javax.swing.JButton r1Down;
    private javax.swing.JLabel r1Label;
    private javax.swing.JButton r1Up;
    private javax.swing.JButton r2Down;
    private javax.swing.JLabel r2Label;
    private javax.swing.JButton r2Up;
    private javax.swing.JToggleButton toFrom;
    private javax.swing.JTextArea translationText;
    // End of variables declaration//GEN-END:variables
}
